### ISSUE TITLE
Tool not loading into certain browsers

### ISSUE THREAD

**Issue by Velonad** [andimiller/br#12]
Hi Lucia & robbilie, just gonna say that's I'm a big fan of you guys getting br doc working again.

So far it's working very smoothly, but I noticed that the tool doesn't seem to load in Microsft Edge, nor in Internet Explorer. 

**This is Microsoft Edge:**
![applicationframehost_2017-10-18_08-46-34](https://user-images.githubusercontent.com/28618861/31704296-e6178fd6-b3e0-11e7-8b8e-ccc476e04b16.png)

**This is Internet Explorer:**
![iexplore_2017-10-18_08-48-02](https://user-images.githubusercontent.com/28618861/31704338-135fe420-b3e1-11e7-9bc2-61ace0849eae.png)

As much as I know :lol-iexplorer-in-tyool-2k17: & :Microsoft_edgy: for being shit browsers, I still think it's a nice thing to know about.

**Comment by andimiller** [comment]
good catch, that's Edge not supporting `async`, I guess I need to run it through babel, ugh

**Comment by andimiller** [comment]
I've now added babel to compile it for old-ass browsers, it should work on Edge at least now, I may explore older IE stuff soon

**Comment by Velonad** [comment]
Can confirm it now works smoothly on edge.

Thanks! 👍
