### ISSUE TITLE
Kill List sort by ISK misbehaving

### ISSUE THREAD

**Issue by irwiss** [andimiller/br#15]
Would be neat to see the highest isk loss mails at a glance

[This is how it currently sorts](https://i.imgur.com/09Ek2zv.png)

As you can see it's getting confused by k/m/b suffixes.

Is it possible to sort by raw isk value rather than cell text?

**Comment by andimiller** [comment]
this is now fixed as of release 0.98, I added a parser that understands the suffixes to the table sorter
